config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py -ID 57765 -R oai-pmh -B http://digital.csic.es/dspace-oai/request
          --tool_endpoint http://localhost:9090/v1.0/rda/rda_all
        container: qc.fair_shabby-sepia-elephant
timeout: 5400
